name: orkitt
description: A professional Flutter UIKit by Orkitt Studio â€” designed to accelerate app development through responsive design, modular components, and brand-driven theming. Build scalable, beautiful, and consistent interfaces with less boilerplate.
publish_to: none
version: 1.1.3+1
homepage: https://github.com/orkitt/uikit
repository: https://github.com/orkitt/uikit
issue_tracker: https://github.com/orkitt/uikit/issues
documentation: https://github.com/orkitt/uikit/wiki

screenshots:
  - description: 'Orkitt UI Framework Icon'
    path: images/icon.png
  - description: 'Orkitt UI Framework Cover Image'
    path: images/cover.jpg
  - description: 'Responsive Layout System'
    path: images/global.jpg
  - description: 'Theming & Components Overview'
    path: images/components.jpg

topics:
  - orkitt
  - responsive
  - theming
  - extensions
  - toolkit

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  orkitt_core: ^0.0.4+1 
   # path: ../orkitt_core
  orkitt_foundation: ^1.0.1
   # path: ../orkitt_foundation
  orkitt_ui: ^0.0.2
    #path: ../orkitt_ui
  orkitt_utils: ^0.0.1
    #path: ../orkitt_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: