name: orkitt
description: A professional Flutter UI framework by Orkitt Studio â€” designed to accelerate app development 
  through responsive design, modular components, and brand-driven theming. 
  Build scalable, beautiful, and consistent interfaces with less boilerplate.

version: 1.0.0-dev
homepage: https://github.com/orkitt/orkitt_framework
repository: https://github.com/orkitt/orkitt_framework
issue_tracker: https://github.com/orkitt/orkitt_framework/issues
documentation: https://github.com/orkitt/orkitt_framework/wiki

screenshots:
  - description: 'Orkitt UI Framework Icon'
    path: images/icon.png
  - description: 'Orkitt UI Framework Cover Image'
    path: images/cover.jpg
  - description: 'Responsive Layout System'
    path: images/responsive.jpg
  - description: 'Theming & Components Overview'
    path: images/components.jpg

topics:
  - orkitt
  - responsive
  - theming
  - extensions
  - toolkit

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  # Update the pubspec.yaml file to include the font in the lib/fonts section.
  assets:
    - lib/src/data/raw/orkitt.png

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
